apiVersion: apps/v1
kind: Deployment
metadata:
  name: what-to-eat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: what-to-eat-api
  template:
    metadata:
      labels:
        app: what-to-eat-api
    spec:
      containers:
        - name: api
          image: asia-east1-docker.pkg.dev/newtest-414721/mlops/what-to-eat-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:///./test.db"
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000" 
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: what-to-eat-api
spec:
  type: LoadBalancer
  selector:
    app: what-to-eat-api
  ports:
    - port: 80
      targetPort: 8000


